// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9K17_s-AlR_aUXJEYjbOe9Y3BQ7qgbw',
    appId: '1:614274060007:web:347c49f5d35a06e87a5c42',
    messagingSenderId: '614274060007',
    projectId: 'app-avaliacao-sweetbah',
    authDomain: 'app-avaliacao-sweetbah.firebaseapp.com',
    storageBucket: 'app-avaliacao-sweetbah.appspot.com',
    measurementId: 'G-T5MBD7S9PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0Qvst52JjEQa5JJAOxOSRrcpMsHHBO4',
    appId: '1:614274060007:android:8b802d585505abb87a5c42',
    messagingSenderId: '614274060007',
    projectId: 'app-avaliacao-sweetbah',
    storageBucket: 'app-avaliacao-sweetbah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2xwqwFmavL2aqG6CHpK7EizAA7xAoj4',
    appId: '1:614274060007:ios:107cbf2557f860277a5c42',
    messagingSenderId: '614274060007',
    projectId: 'app-avaliacao-sweetbah',
    storageBucket: 'app-avaliacao-sweetbah.appspot.com',
    iosClientId:
        '614274060007-n4cbg97mp9d79o3pgol8calgsrk95bkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAvaliacao',
  );
}
